### PR TITLE
Bug/box trigger crash

### PR DESCRIPTION
**Pull request by AniolAndres**
BoxTriggers have now four separate categories:

- PlayerHp
- PlayerAttack
- EnemyHp
- EnemyAttack

The collisions are only detected when a playerHp and EnemyAttack, or a EnemyHp and playerAttack collide.
This solves the bug where the player could deal sometimes double or triple damage through colliding the enemy hitbox attack.

Furthermore, now it should not creash any longer when going through certain types of enemies.

To test please run the Graveyard scene and try your best to crash it or deal double damage to enemies (attacking when they attack).

You can also use an empty scene and make a GO with each type of Box trigger and play with them and check that the collisions are done correctly.

### CODE REVIEW

**Comment by AlfonsoMestres** [comment]
Bandolero's highlight still not working, talk with @Rubetoman he was working in this bug too.

**Comment by Rubetoman** [comment]
> I can't deal damage or get hit :(
> After investigating, I found that the type of trigger checkboxes on the enemies nor the player where checked. After checking them it worked, I think it is because a bug on the prefabs I found.
> 
> Bugs found:
> 
> * [Prefabs] The "sync to prefab" doesn't work ([#887](https://app.hacknplan.com/p/85404/kanban?categoryId=8&boardId=212215&taskId=887&tabId=basicinfo)).
> * There is no way to uncheck the trigger box type. If the trigger box only can be of one type you could use a dropdown instead. (changes requested for this).
> * The multihit bug can still occur if the player looks away from the enemy and back at him to fast. I will try to add my approach to see if it gets fixed, if not I will add task in HnP. [Bug example](https://gyazo.com/c25be7732768d6716b996b8aef824ba6)

Adding my approach doesn't fix the multihit bug, modified HnP task [#875](https://app.hacknplan.com/p/85404/kanban?categoryId=8&boardId=212215&taskId=875&tabId=basicinfo)

**Comment by Rubetoman** [comment]
> Bandolero's highlight still not working, talk with @Rubetoman he was working in this bug too.
> The objective of the PR is fixed, per se, we can accept this PR.
> (Let's open a new PR in order to fix other bugs, etc.)
> 
> Bugs found:
> 
> * UI bar health is not being rendered for multiple enemies [(HnP)](https://app.hacknplan.com/p/85404/kanban?categoryId=8&boardId=212215&taskId=886)
> * Bandolero's highlight not working as expected [(HnP)](https://app.hacknplan.com/p/85404/kanban?categoryId=8&boardId=212215&taskId=880)

The highlight bug has been fixed in PR #286

**Comment by Rubetoman** [comment]
It would be cool for future use to add the type "Other" (or something similar) so the TriggerBoxes can be used for things that are not Enemies or the Player.

**Comment by AniolAndres** [comment]
> It would be cool for future use to add the type "Other" (or something similar) so the TriggerBoxes can be used for things that are not Enemies or the Player.

Done

**Pull request merged**
