### PR TITLE
Adding Cooldown functionality to hud buttons on graveyard

### PR DESCRIPTION
**Pull request by bar0net**
- QWER / 1234 buttons should display cooldown behavior:
  - the button shows a descending gray mask to track the remaining cooldown
  - the button can't be activated while in cooldown

- QWER cooldowns (abilities) are exposed in the editor on the PlayerMovements Script section 
- QWER cooldowns are serializable

### CODE REVIEW

**Comment by AlfonsoMestres** [comment]
We want to establish a Global Cooldown timer to almost every skill so the player cannot click 4 abilities at once. 
Also, it would be nice to be invisible for the user (if we put every shortcut in CoolDown it would be weird to see in the UI). 
This Global CD would affect only to abilities, objects will be insta-casted and no animation will be required (but will trigger some SFX if we are allowed).

**Comment by bar0net** [comment]
Added the posibility to set a "General Ability Cooldown" that would be applied to all abilities when any is used.

For the used ability, it is set to the maximum cooldown between the General Ability Cooldown and it's own (so, if we don't want specific ability cooldowns, we can set it to zero)

Added the possibility to show/hide cooldowns for abilities and items.

**Comment by AlfonsoMestres** [comment]
> Added the posibility to set a "General Ability Cooldown" that would be applied to all abilities when any is used.
> 
> For the used ability, it is set to the maximum cooldown between the General Ability Cooldown and it's own (so, if we don't want specific ability cooldowns, we can set it to zero)
> 
> Added the possibility to show/hide cooldowns for abilities and items.

Thank you Jordi! Nice work!!

**Comment by bar0net** [comment]
Somehow, git gives raises issues when I try to push to a branch names FEATURE but not feature. I'll investigate further.

You should be able to change cooldowns in the editor under player movement script menu.

**Pull request merged**
