### PR TITLE
Feature/items desc

### PR DESCRIPTION
**Pull request by CRomeroP**
To test this PR.

·Check if names are showed correctly over items in terrain (size, and rarity color)
·Pick an item and red point should be showed in inventory button
·In inventory, you can check item description (name, stats and comparation between item showed and item equiped).
·When player level up, red point should be showed in skills button.

In order to test correctly, maybe will be necessary to regenerate navegation mesh

### CODE REVIEW

**Comment by RogerNogue** [comment]
I'm in "Level0-TheGraveyard.sc3ne" and it's not working. Whenever I either open the menu or pickup an item, the next error appears:
image
I tried re compiling and re re compiling everything

**Comment by CRomeroP** [comment]
> * Weird bug on equiping items. The values of stats of each item don't quite sum up. (Look at stats values on equipping / unequiping).
Bug on equiping item solved. Now the values of stats sums properly.
>   BugAddItem
> * Amount of stats that each item will sum up is a little bit misleading, I don't understand it quite. What represent the numbers in green? I think they don't work properly. When equiping another chest the values in green are not correct.
This is solved after the previous bug of values on equiped is resolved. This feature is to compare stats of selected item with equiped item. Numbers in green represents better stats while red numbers represent a lose of stats. With new fonts is possible use "+" and "-" signs, adding it could improve the understanding of this.
>   stats
> * Adding experience using F3 (GodMode) crashes. Seems that "NewSkill" GO is not found.
That was just a tipping error. Now is searching the right GO ("NewSkillPoint").
> * I created a task for the old bug of adding infinite stats on equiping/unequiping item to fix that asap.
Fixed on first comment

**Comment by CRomeroP** [comment]
> * Weird bug on equiping items. The values of stats of each item don't quite sum up. (Look at stats values on equipping / unequiping).
>   BugAddItem
> * Amount of stats that each item will sum up is a little bit misleading, I don't understand it quite. What represent the numbers in green? I think they don't work properly. When equiping another chest the values in green are not correct.
>   stats
> * Adding experience using F3 (GodMode) crashes. Seems that "NewSkill" GO is not found.
> * I created a task for the old bug of adding infinite stats on equiping/unequiping item to fix that asap.

> * Weird bug on equiping items. The values of stats of each item don't quite sum up. (Look at stats values on equipping / unequiping).
Bug on equiping item solved. Now the values of stats sums properly.

> * Amount of stats that each item will sum up is a little bit misleading, I don't understand it quite. What represent the numbers in green? I think they don't work properly. When equiping another chest the values in green are not correct.
This is solved after the previous bug of values on equiped is resolved. This feature is to compare stats of selected item with equiped item. Numbers in green represents better stats while red numbers represent a lose of stats. With new fonts is possible use "+" and "-" signs, adding it could improve the understanding of this.

> * Adding experience using F3 (GodMode) crashes. Seems that "NewSkill" GO is not found.
That was just a tipping error. Now is searching the right GO ("NewSkillPoint").

> * I created a task for the old bug of adding infinite stats on equiping/unequiping item to fix that asap.
Fixed on first comment

**Comment by CRomeroP** [comment]
> * Weird bug on equiping items. The values of stats of each item don't quite sum up. (Look at stats values on equipping / unequiping).
 Bug on equiping item solved. Now the values of stats sums properly.
>   BugAddItem
> * Amount of stats that each item will sum up is a little bit misleading, I don't understand it quite. What represent the numbers in green? I think they don't work properly. When equiping another chest the values in green are not correct.
>   stats
> * Adding experience using F3 (GodMode) crashes. Seems that "NewSkill" GO is not found.
> * I created a task for the old bug of adding infinite stats on equiping/unequiping item to fix that asap.
1. Bug on equiping items solved. Now stats are calculated propertly when player equip and unequip items.
2. This is solved after the previous bug of values on equiped is resolved. This feature is to compare stats of selected item with equiped item. Numbers in green represents better stats while red numbers represent a lose of stats. With new fonts is possible use "+" and "-" signs, adding it could improve the understanding of this.
3. That was just a tipping error. Now is searching the right GO ("NewSkillPoint").
4. Fixed on first comment.

I will add later gifs to HacknPlan task with features working properly since I can't create them at this moment.

**Comment by CRomeroP** [comment]
> I'm in "Level0-TheGraveyard.sc3ne" and it's not working. Whenever I either open the menu or pickup an item, the next error appears:
> image
> I tried re compiling and re re compiling everything

Now should works fine since right GO is searched.

**Pull request merged**
