### PR TITLE
Fix bug in Potions persistence between levels

### PR DESCRIPTION
**Pull request by lluissr**
To test:
- Load level1 and pick some potions.
- Equip potions in the slots (q,w,e,r,...) and play to the level 2
- In the level2 you should see the potions in the correct place, with the correct number and you can use them correctly.

Also test:
. If in the level2 can open and close the inventory and skills and looks correct, not this:
 
0ba705ef5f39f1c285c3862b8f064704

### CODE REVIEW

**Comment by sondy99** [comment]
Yeah I test and I found the same problems, and I took a mana pot and the text did not despair.

<a href="https://gyazo.com/ccac285f91062cf20d0bc0a32858e295">Image from Gyazo</a>

**Comment by lluissr** [comment]
> The potions behaviours are Ok now! Great job <:D
> 
> Found a few issues in the game:
> 
> * The item name flashes on mouse hover (background and text)
>   weirdTitle
> * The menu buttons are not being rendered in the proper position
>   weirdbehavior
> 
> Those changes in the SCENES are located in som prefabs too? If not, be sure before mergin that nobody will override your work.

Try the menu buttons in the second level pls. I think is fixed.

**Comment by lluissr** [comment]
> Yeah I test and I found the same problems, and I took a mana pot and the text did not despair.
> 
> [Image from Gyazo](https://gyazo.com/ccac285f91062cf20d0bc0a32858e295)

Report the errors in the items name to @CRomeroP. The errors are in develop and I tried to fix but I don't understand how works.

**Comment by sondy99** [comment]
The error related to the buttons on the menu are working now, test it again @AlfonsoMestres

**Comment by sondy99** [comment]
> > Yeah I test and I found the same problems, and I took a mana pot and the text did not despair.
> > [Image from Gyazo](https://gyazo.com/ccac285f91062cf20d0bc0a32858e295)
> 
> Report the errors in the items name to @CRomeroP. The errors are in develop and I tried to fix it but I don't understand how works.

@AlfonsoMestres @lluissr I solve this error in this PR so.. one bug less xD gogo xD

**Pull request merged**
