### PR TITLE
pFeature/resolve bug number34

### PR DESCRIPTION
**Pull request by BorjaSasieta**
…object moves to weird positions. Try with spinning top

This bug is produced by:

in a DragFlag3 has limited the position -1000 to 1000.

I resolved it changed the range -100000 to 100000, it's recomendable create a global variable to max position for the max of dimension to scene.

### CODE REVIEW

**Comment by BorjaSasieta** [comment]
> SceneSize should start with a higher default value. Right now, if you open the App and try to move a GO it will break the transform, setting the values to Nan.
> 
> Maybe it would be a good idea to save sceneSize with the scene data and load it on scene load.

is already implemented;)

**Comment by Rubetoman** [comment]
> > SceneSize should start with a higher default value. Right now, if you open the App and try to move a GO it will break the transform, setting the values to Nan.
> > Maybe it would be a good idea to save sceneSize with the scene data and load it on scene load.
> 
> is already implemented;)

It is implemented only on save, not on load.

**Comment by BorjaSasieta** [comment]
rubenator now implement the load.

**Comment by BorjaSasieta** [comment]
now is ready!

**Pull request merged**
