### PR TITLE
Repare sync prefabs

### PR DESCRIPTION
**Pull request by BorjaSasieta**
the variable isPrefabSync now is in constructs and it works

### CODE REVIEW

**Comment by Rubetoman** [comment]
I see you are still working on this branch, close the PR and once you have finished open it.

**Comment by BorjaSasieta** [comment]
@Rubetoman it's finish now

**Comment by Gabroide** [comment]
Once you kill the spider an exception is thrown

image

**Comment by BorjaSasieta** [comment]
now works?

**Comment by AlbertVVila** [comment]
This was not really the problem. **Update to prefab** and **sync with prefab** are different features. **Sync with prefab** allows a gameobject to be updated whenever the prefab is updated in order to have the same features. **Update to prefab** updates de prefab file to this gameobject state and all the other prefab gameobjects that have **sync with prefab**  marked on.
I don't know if you read the wiki about it, you should check it out. If after that you still don't understand, we can discuss it in class.

**Pull request closed without merging**
