### PR TITLE
Added selector to choose default scene

### PR DESCRIPTION
**Pull request by Rubetoman**
Inside ConfigurationPanel->Scene a new selector to choose between scenes has been added.

To test:
- Open the engine.
- Create a scene and save it.
- Go to Configuration->Scene and press Refresh Scenes List button.
- Choose the created scene using the "Default Scene" selector.
- Close the engine.
- Open it again and the scene should be loaded.

### CODE REVIEW

**Comment by Rubetoman** [comment]
> Please do not commit the config.json

It must be changed because before the name of the scene was saved and now the scene UID is saved on the config.json file.

**Comment by Rubetoman** [comment]
> Should be like this in the CleanUp:
> if(defaultScene!= nullptr)
> {
> App->resManager->DeleteResource(defaultScene->GetUID())
> }
> Your code can crash if defaultScene is nullptr and you are not releasing the resource in the resource manager

I've already told you, the Resource Manager deletes all resources of the list on App close, so there is no point in doing that. Also, a ResourceScene doesn't get loaded to memory, you can load the scene on the engine but it doesn't increase any reference number, because only one scene can be loaded at the time.

It shouldn't crash because RELEASE does a nullptr check before deleting a pointer. Have you run the branch on your PC? It can easily be checked that the selected default scene isn't loaded on memory by looking at the Resource Manager Panel, the reference number is kept at 0.

**Comment by AlbertVVila** [comment]
> 
> 
> > Should be like this in the CleanUp:
> > if(defaultScene!= nullptr)
> > {
> > App->resManager->DeleteResource(defaultScene->GetUID())
> > }
> > Your code can crash if defaultScene is nullptr and you are not releasing the resource in the resource manager
> 
> I've already told you, the Resource Manager deletes all resources of the list on App close, so there is no point in doing that. Also, a ResourceScene doesn't get loaded to memory, you can load the scene on the engine but it doesn't increase any reference number, because only one scene can be loaded at the time.
> 
> It shouldn't crash because RELEASE does a nullptr check before deleting a pointer. Have you run the branch on your PC? It can easily be checked that the selected default scene isn't loaded on memory by looking at the Resource Manager Panel, the reference number is kept at 0.

I don't see the resource manager deleting resources on closing the App. Where is it done? I'm debbugging in the RM destructor but he still has the resources map full. The pointers inside should be freed at some point.

**Comment by Rubetoman** [comment]
> > > Should be like this in the CleanUp:
> > > if(defaultScene!= nullptr)
> > > {
> > > App->resManager->DeleteResource(defaultScene->GetUID())
> > > }
> > > Your code can crash if defaultScene is nullptr and you are not releasing the resource in the resource manager
> > 
> > 
> > I've already told you, the Resource Manager deletes all resources of the list on App close, so there is no point in doing that. Also, a ResourceScene doesn't get loaded to memory, you can load the scene on the engine but it doesn't increase any reference number, because only one scene can be loaded at the time.
> > It shouldn't crash because RELEASE does a nullptr check before deleting a pointer. Have you run the branch on your PC? It can easily be checked that the selected default scene isn't loaded on memory by looking at the Resource Manager Panel, the reference number is kept at 0.
> 
> I don't see the resource manager deleting resources on closing the App. Where is it done? I'm debbugging in the RM destructor but he still has the resources map full. The pointers inside should be freed at some point.

But that is a mistake from the RM that should have been reported long ago. To this branch, it only concerns the defaultScene. Anyways, I've added the CleanUp for the RM.

**Pull request merged**
