### PR TITLE
Feature/Panel Browser

### PR DESCRIPTION
**Pull request by Rubetoman**
The panel browser allows the user to view and manage the files from assets. Only the files that are registered on the Resource Manager are shown. 
List of available functions:
- Rename
- Delete
- Import configuration

Considerations:
- Only Image files can change the import configuration.
- FBX are not shown because ResourceMesh is still in development
- If you rename a file it is recommended to save the scene (an old scene could have the old file name saved).

### CODE REVIEW

**Comment by Rubetoman** [comment]
> Through the mainmenu option "Tools->ResourceManager" I don't know if it's supposed to look like that but every resource is empty. Another thing is that the engine crashes once I try to open more than 3 resources.

Thanks for the feedback! On changing between resource types it crased because I forgot telling to close previous type window. I'm not sure what are you refering to with "every resource is empty", could you send me a screenshot? Only the "File" field for Resource Meshes should be empty.

**Comment by AniolAndres** [comment]
> > Through the mainmenu option "Tools->ResourceManager" I don't know if it's supposed to look like that but every resource is empty. Another thing is that the engine crashes once I try to open more than 3 resources.
> 
> Thanks for the feedback! On changing between resource types it crased because I forgot telling to close previous type window. I'm not sure what are you refering to with "every resource is empty", could you send me a screenshot? Only the "File" field for Resource Meshes should be empty.

image

image

**Comment by Rubetoman** [comment]
> > > Through the mainmenu option "Tools->ResourceManager" I don't know if it's supposed to look like that but every resource is empty. Another thing is that the engine crashes once I try to open more than 3 resources.
> > 
> > 
> > Thanks for the feedback! On changing between resource types it crased because I forgot telling to close previous type window. I'm not sure what are you refering to with "every resource is empty", could you send me a screenshot? Only the "File" field for Resource Meshes should be empty.
> 
> image
> 
> image
> 
> This happens for every resource in the list

That should only happen for Resources that are not loaded on memory (References = 0). Because it is not loaded in memory it can't display some of the information, you can load it manually by using the Edit button and increasing the references number. I didn't thought about loading them when displayed on that window to avoid confunsion while debugging. If it happens with all Resources even the ones loaded in memory I would need to take a look.

**Comment by bar0net** [comment]
As a side note, it would be cool if pressing enter after renaming a file behaved like the accept button.

Nevertheless, it's an OK for me!

**Comment by Rubetoman** [comment]
> As a side note, it would be cool if pressing enter after renaming a file behaved like the accept button.
> 
> Nevertheless, it's an OK for me!

True! I will add it to the tasks list.

**Pull request merged**
