### PR TITLE
New Skill Info in skillTree

### PR DESCRIPTION
**Pull request by lluissr**
Now the skill info shown in the skill tree when an unlocked skill is hovered is real. Is not a Mock.

To test: 
- Recompile 
- Load Level0-TheGraveyard and play.
- Open skill tree and hover the skill with the mouse. Check if every skill unlocked has different information.

Note: Some words in the skill description may appear divided in two lines.

### CODE REVIEW

**Comment by AlfonsoMestres** [comment]
What changes did you do on the Graveyard scene? Because we've been working on that scene since two days ago and I posted a message to avoid this kind of PR.
Let's talk about this.

**Comment by Gabroide** [comment]
There is no text about the skill.

image

**Comment by Gabroide** [comment]
And the counter is switched to None value

**Comment by lluissr** [comment]
> There is no text about the skill.
> 
> image

Pls, test it again. I think is fixed now.

**Comment by AlfonsoMestres** [comment]
> Working 10/10
> 
> However, I think we should allow reading the description for locked skills as well.

I think he's right, but let just get this on dev.

**Pull request merged**
