### PR TITLE
Feature/consumable items improvements

### PR DESCRIPTION
**Pull request by sondy99**
This branch contains all in the next image

image

The FX on items consumptions are not super pretty, but I think we should include this pr and the create a new one only to improve the FXs if needed

### CODE REVIEW

**Comment by AlfonsoMestres** [comment]
- Updated W image size

Also, the player is not being rendered in LVL 2 (if this bug is not related to this PR just generate a new bug).
playerNotAppearing

And potions are not working on level 2 load :(

**Comment by sondy99** [comment]
> * Updated W image size
> 
> Also, the player is not being rendered in LVL 2 (if this bug is not related to this PR just generate a new bug).
> playerNotAppearing
> 
> And potions are not working on level 2 load :(
> 
> Also, it gives a critical error on exiting the game.
> 
> image

@AlfonsoMestres Did you test de invisible player on develop?

I just test develop and the invisible player is happening and the crash when closing on the lvl 2 too aaaand the pots toooooo.. soo if are already in develop I think we could create new 3 bugs for that!

Let me know if is happening in develop also for you :P

**Comment by sondy99** [comment]
Hi @Rubetoman I answer bellow your comments :)

> **Main change to make:**
> The game breaks if I go to level 2 with the weapon equipped, try replacing the weapon for the new prefab, as that one is old.

[Don't understand what you suggest to do here :$]


> **Extra:**
> When you have 0 potions left the Item should disappear, or at least if you throw it, it should disappear. I think once a potion has been assigned to a slot it shouldn't disappear when the potion is thrown, it should remain with a 0 in the count (and slightly darker the icon if possible).

[I think we could create a new PR with a new task for doing this if necessary, we should not add new features, only solving bugs and stabilizing the game]

> To fix the invisible player bug, the player should be deleted from the scene and dragged the player prefab back to the scene, then save the scene. However the player can't be deleted as the engine crashes, that's why you need to delete it from the scene file directly.

[And okok nice going to try this, thanks!!! ]

**Comment by Rubetoman** [comment]
> > **Main change to make:**
> > The game breaks if I go to level 2 with the weapon equipped, try replacing the weapon for the new prefab, as that one is old.
> 
> [Don't understand what you suggest to do here :$]
> 
Right now, if you take the "machete" on the floor and equip, once you enter level 2 the engine crashes. Maybe, if you change that item in the scene for the new one (as there was a PR time ago that included new weapons) that bug is solved.

**Comment by Rubetoman** [comment]
>The engine crashes on game build while starting:
>Screenshot
>Screenshot2

Also, take a look at this

**Comment by sondy99** [comment]
> > The engine crashes on game build while starting:
> > Screenshot
> > Screenshot2
> 
> Also, take a look at this

Uppppsss!!!! I think I missed commit one file :P

**Comment by sondy99** [comment]
@Rubetoman and @AlfonsoMestres 

Now is no invisible player in the lvl 2.
In GameBuild is working properly.
Is not crashing when you change from lvl 1 to lvl 2 with the shovel equipped.

And the pots when you change lvl is not working I think @lluissr is working in some bugs with items and thinks when you change from lvl one to lvl 2 and if not.. I could solve this in another pr

:) 

PD: Approved putos

**Pull request merged**
