### PR TITLE
Improve animation efficiency

### PR DESCRIPTION
**Pull request by AniolAndres**
If one of the children of the gameobject containing the animation is volumetric there's a check if it's inside the dynamic arranged GOs to be rendered. If not found the model is not animated.

(Not animated means that the positions and rotations of the bones are not being updated, the instance keeps going on!)

### CODE REVIEW

**Comment by Rubetoman** [comment]
A scene to test the performance increase would be great ;)

**Comment by AniolAndres** [comment]
> Hey Aniol, I have tried to animate first the Zombunny but I havent been able.
> Can you take a look again, and if so give instructions on how did you test it?
> Thx :)

Could you please take a shot of what failed, and please don't use the Zombunny for measurement any longer. Use our models better

**Comment by EnriquePuyol** [comment]
There´s no failed, it just doesnt animate
4990c50861b7d1a7d96e6d885a95df85

**Comment by AniolAndres** [comment]
> There´s no failed, it just doesnt animate
> 4990c50861b7d1a7d96e6d885a95df85

If there's no game camera it won't animate anything since this PR is about frustum culling

**Comment by AniolAndres** [comment]
> Animations not working. Maybe frustum culling is not done properly 🤔
> animations

There was a misplaced break

**Comment by AniolAndres** [comment]
> Working Ok.
> Pls have the pr updated with the last version of develop. I had a lot of problems with the compilating because of this,

Done

**Pull request merged**
