### PR TITLE
Output directories for compilation in Debug and Release set

### PR DESCRIPTION
**Pull request by RogerNogue**
Now the .exe, .pdb, .ilk and all these files are generated in the  Debug and Release files.
Now the function PHYSFS_getBaseDir() does not give the Game folder since it looks fror the output directory. PHYSFS_getWriteDir() has to be used now (this function returns "../Game")

### CODE REVIEW

**Comment by AlfonsoMestres** [comment]
In order to keep the Auto-release working, we need to talk with @bar0net before the merge is done.

**Comment by RogerNogue** [comment]
Now the intermediate directory is also set to ../Debug and ../Release and all files are generated in the specified directory.

**Comment by RogerNogue** [comment]
> Alfonso is right, after the compilation the exe of Debug cannot be executed

According to that, Alfonso just said that the .exe has to be moved manually to the Game folder if someone wants to execute it.

**Comment by EnriquePuyol** [comment]
10/10 would executed again

**Pull request merged**
