### PR TITLE
Feature/post alpha render improvements

### PR DESCRIPTION
**Pull request by solidajenjo**
To test Load RenderTest to see the new features.
Create a camera to test the fog parameters. The first is the linear decay & the second is the quadratic. 

New features:

· Water blends between two textures
· New emitters and random parameters between 2 values in particle systems
· The  particles can be rendered behind alpha meshes
· Volumetric lights
· Camera FOG

### CODE REVIEW

**Comment by Gabroide** [comment]
After runing the engine a exception is displayed.

image

**Comment by solidajenjo** [comment]
> After runing the engine a exception is displayed.
> 
> ![image](https://user-images.githubusercontent.com/23279836/62038129-720bf180-b1f5-11e9-838e-d60d48973fa0.png

This is a bug not related with this PR
It happens sometimes when importing resources. Try to delete the meta whom causes the exception

**Comment by AlbertVVila** [comment]
It happened to me when i switched over to that branch. If it's the meta file which is causing it we should update a new version in this PR to avoid everyone to have the same issue.

**Comment by AlbertVVila** [comment]
I changed it myself 😄

**Comment by solidajenjo** [comment]
Perfect!! Thanks!!

**Pull request merged**
