### PR TITLE
Item pickup enhanced

### PR DESCRIPTION
**Pull request by RogerNogue**
Created new state of player going towards an item to pick it up. To test:
- check that when clicking on an item, it goes towards it to pick it up
- check that if the item is close, it goes and picks it up
- check that if the it em is far, it does not get there
- check that when going for an item the player can switch states and just walk, attack or use skills
- check that UI buttons still work

### CODE REVIEW

**Comment by AlfonsoMestres** [comment]
Removed Lib and recompiled, cannot move and pick when clicking the item.

pickinUpNotWorking

**Comment by AlfonsoMestres** [comment]
pickinUpNotWorking2

**Comment by RogerNogue** [comment]
I made some changes to the feeling. Now when you click on an item, it does not change to walking state until you release the mouse and press again on the floor

**Comment by AlfonsoMestres** [comment]
YEAH, that's literally the feeling we wanted to have when picking up items.
Nice job! My dieses

**Pull request merged**
