### PR TITLE
Detecting Enemy Hover through Bounding Box

### PR DESCRIPTION
**Pull request by bar0net**
Changed hover detection from "raycasting to tris" to "raycasting to bounding box"

Expected behaviour (same as previous behaviour):
- Enemy is highlighted on hover
- Enemy gets attacked on mouse left click (when closed)

---
Unexpected behaviours detected:
- When loading level0-graveyard, main menu does not show
- Player spends mana on melee attack

### CODE REVIEW

**Comment by Gabroide** [comment]
I cannot test it. An assertion error is launched. I am tsting th level0-Graveyard scene.

**Comment by bar0net** [comment]
> I cannot test it. An assertion error is launched. I am tsting th level0-Graveyard scene.

It works on my end. 
I would appreciate if you could provide more details on the error or how to reproduce it.

**Comment by Gabroide** [comment]
This is launched as soon as I push on play.

AssertWindow
Exception

**Comment by AlbertVVila** [comment]
You should checkout the conflicts!

**Comment by bar0net** [comment]
I tend to always check conflicts before merging the branch back to develop.

Note: I added a check instruction in AnimationController to avoid an assertion that raised while checking if the merged version worked properly,

**Pull request merged**
