### PR TITLE
Bug/encoding utf 8 scrpits

### PR DESCRIPTION
**Pull request by BorjaSasieta**
that's all!

### CODE REVIEW

**Comment by AlbertVVila** [comment]
Have you checked that changing the encoding of scripts, allows to compare them in github and auto-merge them correctly? It should be nice to check.

**Comment by BorjaSasieta** [comment]
resolved!

**Comment by AlbertVVila** [comment]
@BorjaSasieta Have you read my old comment? Did you check that the encoding of scripts allow them to be easily compared and merge in github?

**Comment by BorjaSasieta** [comment]
@AlbertVVila I try it and don't work.

can you help me?

Thank you

**Comment by AlbertVVila** [comment]
> 
> 
> @AlbertVVila I try it and don't work.
> 
> can you help me?
> 
> Thank you

We can discuss it on Thursday, try to figure it out yourself. Maybe changing the encoding is not enough to make the cpp not behave as a BIN for github

**Comment by BorjaSasieta** [comment]
Hello I saw this problem has resolved!
Right?

**Pull request closed without merging**
