### PR TITLE
Enemy Dividing

### PR DESCRIPTION
**Pull request by AlbertVVila**
# Features (GIFs describing it are incoming)
- New DividingEnemy. When you are in range he divides itself in 3 basic enemies and runs towards you. Added a particle effect for division and a trail for basic attack.
- Horizontal Scrolling (It was a headache to move in bones hierarchy without resizing the window).
- ReAdded new meta files version
# Necessary Fixes
- Removed "Clone" text after a cloned GameObject. It was a good idea but it added this text to each children aswell. This was a problem for GameObjects reference that were by name.
- Fixed error on removing particle system
- Fixed error on disabling trail or particle system
- Removed on component creation a global position setting
- Fixed error on bone linking in prefab spawn
- Changed Update Transform in order to simplify transform update for dynamic gameobjects

## Feature Testing
- Check that you can scroll horizontally when gameobjects don't fit in the hierarchy window
- Open the EnemiesTest2 scene and check that the new DividingEnemy works as described

### CODE REVIEW

**Comment by AlfonsoMestres** [comment]
d1qvvwf-283ea7d0-45c1-41b6-a843-b6d328d90c9c

Mis desenas...y mi 🍆 

A few elements to improve:

- Enemy life only being displayed in the original ENEMY
- When ran out of their active range they will just walk weirdly to their initial position (they fuse in one weird body)
- The hand trails are too visible, the VFX of Hero being hit will be enough to give him the feeling you are looking for.
- We should add a Dead animation where an explosion of bones + dust should appear when the player lands the fatal blow. (in addition to @AniolAndres PR of "El Enterrador")
- SUGGESTION: We can add a ninja mask in order to make him more naruto..

**Comment by AlbertVVila** [comment]
> 
> 
> d1qvvwf-283ea7d0-45c1-41b6-a843-b6d328d90c9c
> 
> Mis desenas...y mi 🍆
> 
> A few elements to improve:
> 
>     * Enemy life only being displayed in the original ENEMY
> 
>     * When ran out of their active range they will just walk weirdly to their initial position (they fuse in one weird body)
> 
>     * The hand trails are too visible, the VFX of Hero being hit will be enough to give him the feeling you are looking for.
> 
>     * We should add a Dead animation where an explosion of bones + dust should appear when the player lands the fatal blow. (in addition to @AniolAndres PR of "El Enterrador")
> 
>     * SUGGESTION: We can add a ninja mask in order to make him more naruto..

I'll take note of it for enemy improvements 😃

**Comment by RogerNogue** [comment]
It's great! Nice job! Although I found a little wierd behaviour with the targeting:
narutoEnemiesBug

**Comment by AlbertVVila** [comment]
> 
> 
> It's great! Nice job! Although I found a little wierd behaviour with the targeting:
> narutoEnemiesBug

Yes that's because of the hover functionality. It hovers by name and those enemy have the same enemy mesh. There is already a task in HackNPlan to solve that issue.

**Pull request merged**
