### PR TITLE
Feature/pause menu

### PR DESCRIPTION
**Pull request by bar0net**
- Added pause menu
- Exported pause menu as a prefab (BUG: images not loading correctly with the prefab)
- Minor tweaks to component Image

---
TEST:
- You can open/close the pause menu by pressing "P", "ESCAPE", or using the button on the top left
- With the menu open:
  - Resume: should close the pause menu and return to the game
  - Options: not currently implemented
  - Exit: Closes the game

### CODE REVIEW

**Comment by sondy99** [comment]
Hello @bar0net , only a question? it is possible to go back to the "main menu" (I mean the first one) because if not, and if is not a complicated I think is a interesting feature because if someone (like the teachers) could reset the game, could be a nice to have.

What do you think @AlfonsoMestres ?

**Comment by AlbertVVila** [comment]
> 
> 
> coding style
> 
> If(condition)
> {
> //code
> }

@BorjaSasieta quote the specific part of the code that does not fit the requirements

**Comment by BorjaSasieta** [comment]
@AlbertVVila i'm sorry.

**Comment by bar0net** [comment]
Bug detected after merge: player damages enemies by just walking.

DevelopBug

**Comment by AlfonsoMestres** [comment]
> Hello @bar0net , only a question? it is possible to go back to the "main menu" (I mean the first one) because if not, and if is not a complicated I think is a interesting feature because if someone (like the teachers) could reset the game, could be a nice to have.
> 
> What do you think @AlfonsoMestres ?

Yes, we need to be able to exit the game to the Main menu.

**Comment by bar0net** [comment]
Changed *Exit Button* on *Pause Menu* to redirect to the *Main Menu Scene*.

**Pull request merged**
