### PR TITLE
Pause Menu

### PR DESCRIPTION
**Pull request by bar0net**
- Re-built pause menu.
  - Desaturated colors when buttons are not being hovered to allow a color transition from not hovered to hovered (can be easily modified in editor).
  - As an outline for the menu, I used a darkened copy of the background (as a temporary solution?)
  - Stored as a Prefab to ease setting it up in new scenes
- Changed Button Component Behaviour to display "Pressed Image" while mouse 1 is being pressed (down state or repeat state)

**Test:**
- Pause Menu should be displayed when pressing the top left button or the P key
- Resume Button should deactivate the pause menu and resume the game
- Options Button does nothing at this moment
- Exit Button should return the user to the main menu

- All other buttons should work and be displayed as previously intended

**Bug Report:**
- Player does not take damage if standing still
NetaBug

### CODE REVIEW

**Comment by Gabroide** [comment]
I have load the graveyard scene pushed P key and no pause menu, by the other hand, which is the top left button? Left mouse button is to move the player, and right mouse button doesn't show the pause menu.

Am I doing anything wrong'

**Comment by bar0net** [comment]
I encountered some issues after resetting my local project, solved after re-compiling. I have defined some dependencies within the project to generate a functional compilation order (Now, if you press on recompile on the whole solution on VS, it should compile all projects in a proper order).

As for the top-left button, I mean the top-left button on the screen.
NetaPause

**Comment by solidajenjo** [comment]
> I encountered some issues after resetting my local project, solved after re-compiling. I have defined some dependencies within the project to generate a functional compilation order (Now, if you press on recompile on the whole solution on VS, it should compile all projects in a proper order).
> 
> As for the top-left button, I mean the top-left button on the screen.
> NetaPause

Hero!

**Comment by AlfonsoMestres** [comment]
Pause, resume and exit works as expected (In level 1 and level 2). 
Nicely done! 💯 

(Be aware, there are some issues regarding enemies scripts, loading the new game when pressing exit breaks the engine, etc).

**Pull request merged**
