### PR TITLE
LVL0 lighting rework

### PR DESCRIPTION
**Pull request by solidajenjo**
To test Load LVL0 

Changes:

- Lighting rework in LVL0
- Fixed flames flickering
- Fixed materials
- Removed unused DLLs

### CODE REVIEW

**Comment by solidajenjo** [comment]
Fixed crowd controller issues
Added null control on skill tree

**Comment by solidajenjo** [comment]
True. Fixed!

**Comment by AlbertVVila** [comment]
I included two scripts that were outside the Scripts folder

**Comment by solidajenjo** [comment]
Perfect!

**Comment by AlbertVVila** [comment]
I did some fixing in the scene. Now it should be alright. @solidajenjo check if everything is alright
-> Detected a couple of bugs unrelated to this PR, i'll add them to the HackNPlan

**Pull request merged**
