### PR TITLE
Player movement corrections

### PR DESCRIPTION
**Pull request by RogerNogue**
Enhanced the player movement. To test:
- see that when clicking close to the player it now moves.
- see that when clicking outside of nav zone, the player does not start flashing.

### CODE REVIEW

**Comment by RogerNogue** [comment]
There still was a little bug, it got corrected

**Comment by AlfonsoMestres** [comment]
> Great job! But there are still some situations where the player makes the flashing movement. Example:
> https://gyazo.com/bacda2ee3fd6da7312d3af250f17e9fa
> 
> On this gif, the flashing seems less because of the low frame rate.

I think the result we achieved is enough, If the player doesn't find this bug on normal gameplay (Not a debug/test gameplay) we might want to merge this. 
Let's talk with @RogerNogue

**Comment by Rubetoman** [comment]
> > Great job! But there are still some situations where the player makes the flashing movement. Example:
> > https://gyazo.com/bacda2ee3fd6da7312d3af250f17e9fa
> > On this gif, the flashing seems less because of the low frame rate.
> 
> I think the result we achieved is enough, If the player doesn't find this bug on normal gameplay (Not a debug/test gameplay) we want to merge this.
> Let's talk with @RogerNogue

It was found during normal gameplay, I didn't try anything weird.

**Comment by RogerNogue** [comment]
@Rubetoman @AlfonsoMestres 
I really appreciate your time, feedback and opinions! In the last 2 commits I solved the bug that was happening in the gif. It happened when clicking in a place that was not navigable but it was close to the player.

Here is the current state of the player movement after these last commits I made:
Pretty much player does not get stuck between animations in almost any case. The only case it does get stuck is sometimes when the user clicks in a place where there are 2 possible paths. Examples:

bug2Paths
bugPaths2

Since our design of classes, animation states and pathfinding calls was not made thinking of these problems, fixing every single detail would take really long and it is not an option currently. 
Diablo 3 also has some situations with a really similar problem. Example:
https://imgur.com/KFgXhEb

**Pull request merged**
